config/routes.rb
SampleProject::Application.routes.draw do

  
   resources :emails

   resources :users
   
   resources :sessions, :only => [:new, :create, :destroy]

   match '/signup', :to => 'users#new'
   match '/signin', :to => 'sessions#new'
   match '/signout', :to => 'sessions#destroy'
   match '/emails/:id/status', :to => "emails#toggled_status"

  root :to => "home#index"
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :user
  #attr_accessible :from_name,:from_email,:to_email,:subject,:text_body,:user_id,:html_body,:is_published
  #attr_accessible Replaced by Strong Parameters 
   email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


  validates :from_email,   :presence => true,
                      :format => {:with => email_regex}
                     

  validates :to_email, :presence => true,
                      :format => {:with => email_regex}
                     

                      

end

app/models/user.rb
class User < ActiveRecord::Base
  ActiveRecord::Base.send(:include, ActiveModel::ForbiddenAttributesProtection)
  has_many :emails

  attr_accessor :password

  #attr_accessible :name,:email,:password, :password_confirmation
  #attr_accessible Replaced by Strong Parameters 

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,    :presence => true,
                      :length => {:maximum => 50}
  
  validates :email,   :presence => true,
                      :format => {:with => email_regex},
                      :uniqueness => {:case_sensitive => false}

  validates :password,:presence=> true,
                      :confirmation => true,
                      :length => {:within => 6..40}

  before_save :encrypt_password
 
  def has_password?(submitted_password)
  	password_hash == encrypt(submitted_password) 
  end

class << self
	   def authenticate(email,submitted_password)
	    	user = find_by_email(email)
	    	(user && user.has_password?(submitted_password)) ? user: nil
	   end
   
	   def authenticate_with_salt(id,cookie_salt)
	   	  	user = find_by_id(id)
	    	(user && user.password_salt == cookie_salt) ? user : nil
	   end
   
   end

  private 

	  def encrypt_password
	  	self.password_salt = make_salt if new_record?
	  	self.password_hash = encrypt(password)
	  end

	  def encrypt(string)
	  	secure_hash("#{password_salt}--#{string}")
	  end

	  def make_salt
	  	secure_hash("#{Time.now.utc}--#{password}")
	  end

	  def secure_hash(string)
	  	Digest::SHA2.hexdigest(string)
	  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_filter :authenticate, :only => [:index,:edit,:update,:destroy]
  respond_to :html, :json
  
  def index
    @emails = current_user.emails
  end

  def new
    @email = Email.new
  end

  def create
    @email = Email.new(email_params)
    if @email.save
       redirect_to @email, :flash => {:success => "Welcome #{current_user.name}"}
    else
      render 'new'
    end
  end

  def show
    @email = Email.find(params[:id])  
  end

  def edit
     @email = Email.find(params[:id])
  end

  def update
    @email = Email.find(params[:id])
    if @email.update_attributes(email_params)
      flash[:notice] = "Successfully updated"
       respond_with @user
      #redirect_to @email
    else
      render :action => 'edit'
    end
  end

  def destroy
    @email = Email.find(params[:id])
    @email.destroy
    redirect_to @email
  end

    def  toggled_status
    @email = Email.find(params[:id])
    @email.is_published = !@email.is_published?
    @email.save!
    redirect_to emails_path
  end

   private
   
   def authenticate
     deny_access unless signed_in?
   end
   
   #attr_accessible Replaced by Strong Parameters 
   def email_params
       params.require(:email).permit(:from_name,:from_email,:to_email,:subject,:text_body,:user_id,:html_body,:is_published)
   end
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

   
 def create
  user = User.authenticate(params[:session][:email],params[:session][:password])
  if user.nil?
    flash.now[:error] = "Invalid email/password combination."
    @title = "Sign in"
    render 'new'
  else
    sign_in user
    redirect_back_or(user)
  end
end
  
  def destroy
    sign_out
	redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index,:edit,:update,:destroy]
  before_filter :correct_user, :only => [:edit,:update,:show]
  
  def index
    @users = User.all
  end
  
  
  def show
    @user = User.find(params[:id])
    @emails = current_user.emails
   end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user, :flash => {:success => "Welcome #{@user.name}"}
    else
      render 'new'
    end
   end
   
   def edit
  	@user = User.find(params[:id])
   end
   
   def update
      @user = User.find(params[:id])
     if @user.update_attributes(user_params)
      
       redirect_to @user, :flash => {:success => "Profile updated."}
     else
        @title = "Edit user"
        render 'edit'
     end
   end
   
   def destroy
     User.find(params[:id]).destroy
     redirect_to users_path, :flash => {:success => "User destroyed"}
   end
   
   private
   
   def authenticate
     deny_access unless signed_in?
   end
   
   def correct_user
     @user = User.find(params[:id])
     redirect_to root_path,  alert: 'Unauthorised access to you' unless current_user?(@user)
   end
   
    #attr_accessible Replaced by Strong Parameters 	  
    	  def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
	  def format_boolean(status)
        if status
          icon_tick
        else
          icon_cross
        end
      end
      
      def icon_tick(alt_text='Tick')
        build_image_tag("/assets/001_06.png", alt_text)
      end

      def icon_cross(alt_text='Cross')
        build_image_tag("/assets/001_05.png", alt_text)
      end
      
      def build_image_tag(image_file, alt_text)
        image_tag(image_file, :size =>"20x20", :alt => alt_text)
      end
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.password_salt]
    current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
   
   def current_user?(user)
     user == current_user     
   end
  
   def deny_access
      store_location
     redirect_to signin_path , :notice => "Please sign in to access this page.."
   end
  
    def store_location
      session[:return_to] = request.fullpath
    end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default) #redirecting to the page user wanted to access
    clear_redirect_to
  end
  
  def clear_redirect_to
    session[:return_to] = nil
  end
  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleProject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<ul>
		<li><%= link_to "Home", root_path%></li>
		<% if signed_in? %>
		<li><%= link_to "Profile" , current_user %></li>
		<li><%= link_to "Emails" , emails_path %></li>
		<li><%= link_to "Settings",edit_user_path(current_user) %></li>
		<% end %>
		<% if signed_in? %>
			<li><%= link_to "Sign out",signout_path %></li>
		<% else %>
			<li><%= link_to "Sign in", signin_path%></li>
			<li><%= link_to "Sign up now!",signup_path %></li>
		<% end %>
	</ul>
			
<% flash.each do |key,value|%>
	<%= value %>
<% end %>
<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if controller_name == "emails" %>

		<% if @email.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@email.errors.count,"error") %>
				Prohibited this email from being saved:
			</h2>
			<p>
				There were problems with the following fields:
			</p>
			<ul>
			<% @email.errors.full_messages.each do |message|%>
			 <li><%= message%></li>
			 <% end %>

		</div>

		<% end %>

<% else %>
		<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@user.errors.count,"error") %>
				Prohibited this user from being saved:
			</h2>
			<p>
				There were problems with the following fields:
			</p>
			<ul>
			<% @user.errors.full_messages.each do |message|%>
			 <li><%= message%></li>
			 <% end %>

		</div>

		<% end %>
<%end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages'%>
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name%>
</div>
<div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email%>
</div>
<div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password%>
</div>
<div class="field">
	<%= f.label :password_confirmation,"Confirmation" %><br />
	<%= f.password_field :password_confirmation%>
</div>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= form_for(@user) do |f| %>
<%= render 'fields',:f => f %>
<div class="actions">
<%= f.submit "Update" %>
</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages'%>
<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>
<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>
<div class="field">
<%= f.label :password %><br />
<%= f.password_field :password %>
</div>
<div class="field">
<%= f.label :password_confirmation, "Confirmation" %><br />
<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
<%= f.submit "Sign up" %>
</div>
<% end %>

app/views/users/show.html.erb
Name : <%=@user.name %> <br />
Email :<%= @user.email %><br /><br />
<%= render 'emails/list_email' %>
<%= link_to "Create Email", new_email_path %>